# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'SiFli-Wiki'
copyright = '2025, SiFli'
author = 'SiFli'

# The full version, including alpha/beta/rc tags
release = 'v1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_design",
    #makrdown支持
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_sitemap"
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'shibuya'
#自动编号
numfig = True
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_logo = './_static/logo_white.png'
html_favicon = './_static/logo_favicon.png'

html_css_files = [
    'custom.css',
    'lightbox.css',
]
html_js_files = [
    'js/baidu.js',
    'js/chatbot.js',
    'js/custom.js',
    'js/lightbox.js',
]
html_theme_options = {
        "accent_color": "blue",
        "announcement": """
            <div style="text-align: center">
                思澈 Solution 全面开放：一套产品级方案，加速从原型到量产
                <a href='https://docs.sifli.com/projects/solution/0.introduction/index.html'>Solution文档</a>。
            </div>
        """,
    # "globaltoc_expand_depth": ,
        "github_url": "https://github.com/OpenSiFli",
        "nav_links": [
        {
            "title": "入门指南",
            "url": "docs/index",
        },
        {
            "title": "API文档",
            "url": "https://docs.sifli.com/projects/sdk/latest/sf32lb52x/index.html",
            "external": True,
        },
                {
            "title": "Solution文档",
            "url": "https://docs.sifli.com/projects/solution/0.introduction/index.html",
            "external": True,
        },
        {
            "title": "关于我们",
            "url": "about/index",
        },
    ],
}


myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "attrs_block",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

html_baseurl = 'https://wiki.sifli.com/'
sitemap_url_scheme = "{link}"
sitemap_filename = "sitemap.xml"
sitemap_locales = []

myst_fence_as_directive = ["mermaid"]

html_context = {
    "languages": [
        ("English", "/en/%s.html", "en"),
        ("中文", "/%s.html", "zh"),
    ],
    "source_type": "github",
    "source_user": "OpenSiFli",
    "source_repo": "SiFli-Wiki",
    "source_version": "main",  # Optional
    "source_docs_path": "/source/",  # Optional
}

def setup(app):
    global language, html_baseurl, sitemap_filename, sitemap_locales,html_theme_options,html_context
    language = app.config.language
    if language == 'en':
        html_baseurl = 'https://wiki.sifli.com/en/'
        sitemap_filename = "../sitemap.xml"
        sitemap_locales = [None]
        html_theme_options['nav_links'] = [
        {
            "title": "User Guide",
            "url": "docs/index",
        },
        {
            "title": "Examples",
            "url": "https://docs.sifli.com/projects/sdk/v2.3/sf32lb52x/example/hal/index.html",
            "external": True,
        },
        {
            "title": "API Documentation",
            "url": "https://docs.sifli.com/projects/sdk/v2.3/sf32lb52x/api/index.html",
            "external": True,
        },
        {
            "title": "About Us",
            "url": "about/index",
        },
    ]

    


    